version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sportstore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sportstore_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportstore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
